#!/usr/bin/perl -w

package esmith;

use strict;
use Errno;
use NethServer::Password;
### Creation of the user Admin with all permissions

  my $password = NethServer::Password::store('mysql')
        || die('Could not retrieve mysql password!');
  my $admin_condition = `/usr/bin/mysql103 -e " SELECT EXISTS(SELECT 1 FROM mysql.user WHERE user = 'admin');"`;

if ($admin_condition =~ '0')

    {
    my $commands = join("\n",
        "GRANT ALL PRIVILEGES ON *.* TO 'admin'\@'localhost' IDENTIFIED BY '$password' WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0
         MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;") . "\n";
    print $commands;

    open(FH, '|-', '/usr/bin/mysql103 -B -f') || die("[ERROR] Could not connect to mysql");
    print FH $commands;
    close(FH);
    }

exit (0);
