#!/usr/bin/perl -w

package esmith;

use strict;
use Errno;
use esmith::ConfigDB;
use NethServer::Password;
exit(0) unless system('/usr/bin/mysql103 phpmyadmin  -e "describe pma_userconfig" &> /dev/null') != 0;

### Creation of the mysql base for phpmyadmin

# creation of a password
  my $pass = NethServer::Password::store('phpmyadmin') || die('Could not generate phpmyadmin password!');

#mysql works
  my $commands = join("\n",
                 "GRANT ALL PRIVILEGES ON `phpmyadmin`.* TO 'phpmyadmin'\@'localhost' IDENTIFIED BY '$pass';",
                 "FLUSH PRIVILEGES;",
                 "CREATE DATABASE IF NOT EXISTS phpmyadmin DEFAULT CHARACTER SET = 'utf8';",
                 "USE mysql;",
                 "REPLACE INTO user (host,user,password) VALUES ('localhost','phpmyadmin', PASSWORD ('$pass'));",
                 "REPLACE INTO db (host,db,user,select_priv, insert_priv, update_priv, delete_priv,create_priv, 
                     alter_priv, index_priv, drop_priv, create_tmp_table_priv,grant_priv, 
                     lock_tables_priv, references_priv) 
                  VALUES ( 'localhost','phpmyadmin','phpmyadmin','Y', 'Y', 'Y', 'Y','Y', 'Y', 'Y', 'Y', 'Y','N', 'Y', 'Y');"
) . "\n";

   print $commands;
   open(FH, '|-', '/usr/bin/mysql103 -B -f') || die("[ERROR] Could not connect to mysql");
   print FH $commands;
   close(FH);

# import the phpmyadmin sql structure
   if (-f '/usr/share/phpMyAdmin/sql/create_tables.sql') {
   system ("/usr/bin/mysql103 phpmyadmin < '/usr/share/phpMyAdmin/sql/create_tables.sql'");
   }
